spring.application.name=first-ai-project
server.port=8081

# API Key obtained from Google AI Studio
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# Optional: Specify the model version (defaults vary)
# spring.ai.google.genai.chat.model=gemini-3.5-flash

# Enable Google GenAI Chat Model
spring.ai.model.chat.enabled=true

logging.level.org.springframework.ai.chat.client.advisor=DEBUG